#!/bin/bash

echo "cd home"
cd
echo "download"
wget https://github.com/jakefinkel/PrintManager/archive/master.zip
echo "extract"
unzip master.zip
echo "cd PrintManager-master"
cd PrintManager-master
echo "browse to: http://localhost:8080"
echo "starting PHP"
php -S localhost:8080 &
nautilus .
exit 0
